### PR TITLE
Multiple changes by Szymon

### PR DESCRIPTION
**Pull request by pragmaware**
Not really a proper general fix as the authentication remains expired...

### CODE REVIEW

**Comment by giohappy** [comment]
So with this fix what's happening? The user is redirected to the login page?

**Comment by pragmaware** [comment]
It simply doesn't crash, but following requests fail anyway.
I see this is kind of generalized in the app, when the authentication expires the requests fail and nothing is displayed.

**Comment by pragmaware** [comment]
I think that the correct action is to refresh the token and retry the request. But it should probably be done at request level, not in every place a request is made.

**Comment by giohappy** [comment]
@offtherailz wasn't this already addressed? If it isn't working correctly we should fix it, I don't want to leave the user in a unrecoverable status (i.e. being forced to close and reooen the app)

**Comment by giohappy** [comment]
I missed the note inside the description of this PR: https://github.com/geosolutions-it/smb-app/pull/25

@pragmaware how much do you think it will take to implement token refreh?

**Comment by pragmaware** [comment]
I've taken a look at the token refresh. The process needs to be asynchronous and it looks like all the existing network calls must be slightly refactored. I guess it will take at least a night to fix them all and re-test everything.

**Comment by pragmaware** [comment]
A night wasn't sufficient :) Need to rework the LoginActivity and centralize the Auth process. Another night at least.

**Comment by pragmaware** [comment]
It's done.

**Comment by pragmaware** [comment]
Do we have a bugtracker for the server side? There is an issue with the firebase token registration service. I think it assumes that no more than one device token can be present for each user and it crashes.

**Comment by giohappy** [comment]
@pragmaware yes it is https://github.com/geosolutions-it/smb-portal.
Please submit the issue.

**Pull request merged**
